typography_spectrum: 0.9314793800003827
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.8524880628101528
  lightness: 0.59070092625916
  saturation: 0.06667085038498044
  rhythmicContrast: 0.3461153192911297
opengraph:
  image: null
  type: null
  appId: LovelyOlivesClub
layout_spectrum: 0.18080422305501997
analytics:
  google: null
  facebook: null
  twitter: null
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/5a5aa6b7-6d51-4973-b305-c567b055b39d.jpg
name: LovelyOlives
cta:
  domain: null
  bucket: null
  version: null
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/3c063c3a-8885-4bee-8c3d-602a27788d07.png
purpose: []
